# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks: 
  proxynet:
    driver: bridge
services:
  servicesystemnrdcl:
    image: servicesystemnrdcl
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"
    networks: 
      - proxynet
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - postgres
  postgres:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nrdcldb
    ports: 
      - "5432:5432"
    networks: 
      - proxynet





